# Generated by Django 4.1.4 on 2022-12-14 00:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('co_autor', models.CharField(blank=True, max_length=30, null=True)),
                ('data_cadastro', models.DateField(default=datetime.date(2022, 12, 13))),
                ('emprestado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emprestado', models.CharField(max_length=30)),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField(null=True)),
                ('livro_emprestado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livros')),
            ],
        ),
    ]
