# Generated by Django 4.1.4 on 2022-12-14 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_emprestimos_options_alter_livros_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 14, 2, 3, 502283, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 14, 2, 3, 501992, tzinfo=datetime.timezone.utc)),
        ),
    ]
