# Generated by Django 4.1.4 on 2022-12-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_categorias_livros_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='duracao_emprestimo',
        ),
    ]
