# Generated by Django 4.1.4 on 2022-12-16 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livro', '0006_remove_emprestimos_duracao_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='nome_emprestado',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='pessoa_emprestado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='livros',
            name='co_autor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='nome',
            field=models.CharField(max_length=250),
        ),
    ]
