# Generated by Django 4.1.4 on 2022-12-16 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livro', '0007_remove_emprestimos_nome_emprestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='livro_emprestado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livro.livros'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='pessoa_emprestado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
