# Generated by Django 4.1.4 on 2022-12-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0008_alter_emprestimos_livro_emprestado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='pessoa_emprestado',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='nome_emprestado',
            field=models.CharField(default='sem nome', max_length=255),
        ),
    ]
