# Generated by Django 4.1.4 on 2022-12-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_remove_emprestimos_pessoa_emprestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
